### ISSUE TITLE
0.92 doesn't work on the Steam Deck. Old versions works though.

### ISSUE THREAD

**Issue by MrYoso** [Lyall/HundredHeroesFix#11]
The latest version doesn't work on the Steam Deck, screen stays 16:9. The 2 old versions works perfectly though.

**Comment by Lyall** [comment]
This is expected. In the last update I changed it so that the UI patches only happened when the aspect ratio was higher than 16:9. This is mainly to avoid the overhead of running patches when not necessary. I haven't actually done any testing on <16:9 yet but it is on my to-do list. 

Did you run in to many UI issues prior with the pre-0.9.2 version?

**Comment by Lyall** [comment]
Okay, in v0.9.3 I've added explicit support for <16:9 displays (like the Steam Deck). That means you'll get the UI fixes that ultrawide displays get too. I've also added an extra fix for the camera FOV so that instead of being cropped, it'll expand the field of view vertically.

**Comment by MrYoso** [comment]
> Okay, in v0.9.3 I've added explicit support for <16:9 displays (like the Steam Deck). That means you'll get the UI fixes that ultrawide displays get too. I've also added an extra fix for the camera FOV so that instead of being cropped, it'll expand the field of view vertically.

Tried the latest version on my Steam Deck and I can confirm that it works perfectly and the UI also looks lovely. The blurred background when going in the menu or map is covering the whole screen now. Thanks!
