### ISSUE TITLE
Anti-aliasing, not working?

### ISSUE THREAD

**Issue by RhanCandia** [Lyall/HundredHeroesFix#16]
I enabled AntiAliasing in the config file but I am not sure it works. There are some objects that are so jaggy.

![image](https://github.com/Lyall/HundredHeroesFix/assets/7951366/99a72f32-449b-4524-ad14-d6343d92f18d)

![image](https://github.com/Lyall/HundredHeroesFix/assets/7951366/f313c8e9-122a-459c-8194-82859486e6b5)

Most of the stuff looks okay like the tree leaves, the plants.

Also, a separate thing, I noticed that the enemy sprites are animating in such a slow framerate that they stand out too much when playing in high refresh rate monitors. Is that something that BepInEx is capable of adjusting?

**Comment by Lyall** [comment]
Regarding the anti-aliasing; It's a very light-touch post-process AA in the form of SMAA. It can be hard to spot differences in certain scenes to be honest given how ineffective it can be. If you have `[Info   :HundredHeroesFix] Graphical Tweaks: Enabled high quality SMAA on Main Camera.` in your log though then you can be certain that SMAA has been enabled.

I did look briefly at MSAA which would help a lot with non-specular aliasing but it's incompatible with the rendering setup the game uses. Also TAA isn't an option since this game uses URP and as far as I know, Unity's TAA has not been ported to that yet.
Your most effective remedy for aliasing in this game is either using (DL)DSR/VSR/high render scale along with enabling SMAA.

As for the enemy sprites framerate, I had a poke around and I couldn't find anything that would let me alter either the framerate or enable interpolation during run-time. I think it would need to be something enabled by the devs. Though I imagine that's unlikely given the lower-framerate look is likely intentional.

**Comment by RhanCandia** [comment]
I will try a higher render resolution in the config. I will let you know how it goes. 

Re: enemy sprites, I understand. This is probably by design. But I don’t like it. It hurts my eyes seeing them stutter while everything else is smooth. But that’s just how the devs designed it.

**Comment by RhanCandia** [comment]
@Lyall I tried doubling the internal rendering resolution and it did help mitigate the jaggedness but only by little. And the performance hit on my machine is huge. So, I guess that's not for me.

Maybe one day BepInEx can inject upscaling tech to the game like XeSS or FSR and we can utilize those upscaler tech's anti-aliasing.

I will get around it by using ReShade for now.

I will close this issue now. Thanks!
