### ISSUE TITLE
AMD?

### ISSUE THREAD

**Issue by porkbob** [Lyall/HundredHeroesFix#2]
I tried this, and it indeed skipped the intro movie, but none of the graphic tweaks did anything. The easiest check is returning to Arenside for those insanely pixelated shadows like in your example image. But nope they are exactly the same, as well as low LOD for loading shadows/postprocessing out on the world map and in Arenside/Eltisweiss.

I have a RX 7900XT, so my first thought is maybe this is hardcoded in a way that is only going to work with Nvidia? (I know almost nothing about coding, so forgive any ignorance.)

**Comment by Lyall** [comment]
It's unlikely to be related to GPU vendor. Can you post your `LogOutput.log` file from the `BepInEx` folder? Also, I saw the game got a new update today on Steam but I'm using the Gamepass version so it could be a version issue.

**Comment by porkbob** [comment]
Could be the version thing. I saw people sharing it and saying "Thanks" in the steam forums, but no one actually confirmed verbally if it worked.
[LogOutput.log](https://github.com/Lyall/HundredHeroesFix/files/15121980/LogOutput.log)
[ErrorLog.log](https://github.com/Lyall/HundredHeroesFix/files/15121981/ErrorLog.log)
Attached logoutput and the errorlog

**Comment by Lyall** [comment]
Hmm, your log looks good, it looks like it's applying correctly. Can you try with the shadow resolution set to 5 (4096) for example? Should be a really stark and obvious difference from the game's default of 3 (1024). If that doesn't work then I can add some more logging and give you a test build to try.

**Comment by porkbob** [comment]
Okay, this is more or less a case of it being on me. I assumed that the default settings would be somewhat higher and didn't really look at the config file to see what the options were.
shadow 3:
![shadow_res_3](https://github.com/Lyall/HundredHeroesFix/assets/23653103/3144bac6-f7b0-4100-bbff-5c567c57ef55)

shadow 5:
![shadow_res_5](https://github.com/Lyall/HundredHeroesFix/assets/23653103/0a6c862f-668c-4142-9cbc-1a15f6f47d81)
The default looked basically like the vanilla game to me, but it is noticeably different on 5. And if I crank up the shadow distance it looks great around the game, even if there are some shadows that are a bit aliased even with SMAA and 2x supersampling on (but I figure there is not much you can do with that given what we're working with).

Anyway, apologies and thanks for the effort on this!

**Comment by Lyall** [comment]
No worries, glad it's working for you. The default values are basically just set to the "high" setting so that people have it for reference when scaling up the settings. In the next version the graphical tweaks will be disabled by default (out of consideration for low end PCs, Steam Deck etc) so people will be forced to head over to the config file anyway. 

I've also just added in the latest version (v0.9.1) an option for 8K shadows, if you have the performance to spare it produces pretty pin-sharp results. I also added a shadow cascade option so you can increase it from the default of 3 to 4. I recommend keeping the shadow distance at 150 if you do increase the shadow cascade count though. At this point we're pretty much at the limits of the universal rendering pipeline that this game uses. It's generally intended for high-performance so some settings are relatively conservative.

Feel free to open another issue if you run in to any problems!
