### ISSUE TITLE
MSAA Option

### ISSUE THREAD

**Issue by shinra358** [Lyall/HundredHeroesFix#9]
Requesting MSAA option. For some reason I can never see a difference with smaa in any game and MSAA is usually the go to for a prominant difference in AA tech. I promise this is the last one lol

**Comment by Lyall** [comment]
Here's what happens when you enable MSAA.

Before:
![EiyudenChronicle_2024_04_27_17_42_29_352](https://github.com/Lyall/HundredHeroesFix/assets/695941/019d75df-6fd2-4102-80e8-9e5fdca0d184)

After:
![EiyudenChronicle_2024_04_27_17_42_34_275](https://github.com/Lyall/HundredHeroesFix/assets/695941/fe3fae48-06ed-4be7-9fcc-b9b443f70e6a)

**Comment by shinra358** [comment]
yikes lol. is that because depth isnt unlocked by default or because devs didnt code textures a certain way?

**Comment by Lyall** [comment]
So after a bunch of experimenting I can't get MSAA to work with the other graphical effects intact. It's just incompatible with the rendering setup of the game. For now for best results image quality wise, you'll need to take advantage of SMAA + downsampling from a higher resolution.
